"""Run the replay fixtures against the real Reader and Writer and write docs/live-transcripts.md.

Usage: python scripts/live_replay.py [scenario ...]   (needs ANTHROPIC_API_KEY in .env; costs API calls)

State expectations (phase, verification, pending ask, escalation, counters, outbox) and the leak checks
(reply_not_contains, guard verdict) are hard checks; so is a turn the model never answered (a Reader or Writer
failure). reply_contains wording checks are reported as soft mismatches, because a live Writer paraphrases
must_say lines. Exit code 1 when any hard check fails. The transcript file is written only for a full run.
"""
import json
import os
import sys
import time
import traceback
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.chdir(ROOT)  # .env, fixtures/ and traces/ resolve against the current directory
sys.path.insert(0, str(ROOT))

from app.config import get_settings  # noqa: E402
from app.engine.service import TROUBLE, build_service  # noqa: E402
from app.observability.logging import configure_logging  # noqa: E402
from tests.replay.runner import EXPECT_KEYS, load, scenario_names  # noqa: E402

HARD_KEYS = sorted(EXPECT_KEYS - {"reply_contains", "reply_not_contains", "guard_ok"})
OUT = ROOT / "docs" / "live-transcripts.md"


def run_scenario(name: str, settings) -> dict:
    spec = load(name)
    today = date.fromisoformat(spec.get("today", "2026-10-07"))
    svc = build_service(settings, today=lambda: today)
    session = svc.start(spec.get("scenario", "default"))
    turns = []
    for i, t in enumerate(spec["turns"]):
        t0 = time.perf_counter()
        res = svc.chat(session, t["user"])
        secs = round(time.perf_counter() - t0, 1)
        e = t.get("expect", {})
        s = session
        actual = {
            "phase": s.phase.value, "verified": s.verification.status == "verified",
            "party_id": s.verification.party_id, "attempts": s.verification.attempts,
            "pending_ask": s.pending_ask.value, "escalated": s.escalation.requested,
            "off_topic": s.counters.off_topic, "outbox_len": len(svc.outbox(s)),
        }
        hard = [f"{k}: expected {e[k]!r}, got {actual[k]!r}" for k in HARD_KEYS
                if k in e and actual[k] != e[k]]
        low = res.reply.lower()
        hard += [f"leaked {sub!r}" for sub in e.get("reply_not_contains", []) if sub.lower() in low]
        soft = [f"missing {sub!r}" for sub in e.get("reply_contains", []) if sub.lower() not in low]
        # this turn's verdict; None when no model ran (closed session, Reader failure)
        g = res.trace.get("guard")
        if res.reply == TROUBLE or (g or {}).get("fallback") == "llm_error":
            hard.append("model call failed")
        if "guard_ok" in e:
            ok = g is not None and ((g["ok"] and not g.get("fallback")) if e["guard_ok"] else not g["ok"])
            if not ok:
                hard.append(f"guard: expected ok={e['guard_ok']}, got {g}")
        turns.append({"i": i + 1, "user": t["user"], "reply": res.reply, "actual": actual, "guard": g,
                      "hard": hard, "soft": soft, "secs": secs})
    return {"name": name, "turns": turns}


def guard_text(g: dict | None) -> str:
    if g is None:
        return "no model call"
    if g.get("ok") and not g.get("fallback"):
        return "ok (regenerated)" if g.get("regenerated") else "ok"
    return json.dumps(g)


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def write_markdown(results: list[dict], settings) -> None:
    lines = ["# Live-model transcripts", "",
             f"Generated by `scripts/live_replay.py` with Reader `{settings.reader_model}` and Writer "
             f"`{settings.writer_model}`. Hard checks are the fixture's state and leak expectations; soft "
             "checks are its wording expectations, which a live Writer may paraphrase.", ""]
    for r in results:
        lines += [f"## {r['name']}", ""]
        if "error" in r:
            lines += ["```", r["error"], "```", ""]
            continue
        lines.append("| # | Caller says | Reply | Phase after | Verified | Pending ask | Guard | Secs "
                     "| Checks |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for t in r["turns"]:
            a = t["actual"]
            checks = "; ".join(["HARD " + h for h in t["hard"]] + ["soft " + s for s in t["soft"]]) or "pass"
            lines.append(f"| {t['i']} | {cell(t['user'])} | {cell(t['reply'])} | {a['phase']} | "
                         f"{'yes' if a['verified'] else 'no'} | {a['pending_ask']} | "
                         f"{cell(guard_text(t['guard']))} | {t['secs']} | {cell(checks)} |")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    settings = get_settings()
    configure_logging(settings.log_level)
    names = sys.argv[1:] or scenario_names()
    results, failed = [], 0
    for name in names:
        print(f"== {name}", flush=True)
        try:
            r = run_scenario(name, settings)
        except Exception as exc:  # keep going; the transcript records the failure without local paths
            results.append({"name": name, "error": f"{type(exc).__name__}: {exc}"})
            failed += 1
            print(traceback.format_exc(), flush=True)
            continue
        results.append(r)
        for t in r["turns"]:
            flag = "HARD" if t["hard"] else ("soft" if t["soft"] else "ok")
            a = t["actual"]
            print(f"  T{t['i']} {flag:4} {a['phase']} verified={a['verified']} pending={a['pending_ask']} "
                  f"guard={guard_text(t['guard'])} {t['secs']}s", flush=True)
            for line in t["hard"]:
                print(f"       HARD {line}", flush=True)
            for line in t["soft"]:
                print(f"       soft {line}", flush=True)
        failed += any(t["hard"] for t in r["turns"])
    if not sys.argv[1:]:  # a subset run never overwrites the full record
        write_markdown(results, settings)
        print(f"wrote {OUT}")
    print(f"{len(results) - failed}/{len(results)} scenarios without hard failures")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
